-- Table "film" + RLS: lecture publique, écriture réservée aux utilisateurs authentifiés (admin).

create table if not exists public.films (
  id bigint generated by default as identity primary key,
  titre text not null,
  duree integer not null,
  "anneeDiffusion" integer not null,
  "lienVisionnage" text,
  "qualiteSousTitres" text not null check ("qualiteSousTitres" in ('professionnelle', 'amateur')),
  "auteurSousTitres" text,
  description text not null,
  "vignetteUrl" text not null,
  realisateurs text not null,
  "sousTitresIncrustes" boolean not null default false,
  sme boolean not null default false,
  vost boolean not null default false,
  vf boolean not null default false,
  lsf boolean not null default false,
  ad boolean not null default false,
  publie boolean not null default false
);

alter table public.films enable row level security;

create policy "Films visibles par tous"
  on public.films
  for select
  to public
  using (true);

create policy "Films créables par les utilisateurs authentifiés"
  on public.films
  for insert
  to authenticated
  with check (true);

create policy "Films modifiables par les utilisateurs authentifiés"
  on public.films
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Films supprimables par les utilisateurs authentifiés"
  on public.films
  for delete
  to authenticated
  using (true);
